modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="phenomena" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Phenomena Structures" #mandatory
credits="Thanks for this mod goes to Java!"
authors="Davidak(davidgmc18)" #optional
description='''
Adding structures!!!
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.phenomena]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    side="SERVER"